Repository alkemyTech/OT139-CLIENT, pull requests merged in 2022-03, with the labels that each got.

#12 Ot-139-23-Formulario Registro
  package-lock.json
  package.json
  src/Componets/Auth/RegisterForm.jsx
  src/Componets/Auth/registerForm.css
Labels: enhancement

#17 OT139-26 Screen Mi Perfil
  public/images/assets/page-not-found.svg
  src/components/ErrorCard/ErrorCard.jsx
  src/components/ErrorCard/errorCard.css
  src/components/LoadingCard/LoadingCard.jsx
  src/components/MyProfile/MyProfile.jsx
  src/components/MyProfile/myProfile.css
Labels: enhancement

#4 OT139-19 setup-loader create
  package-lock.json
  package.json
  src/App.js
  src/components/loader/Loader.jsx
  src/components/loader/loader.css
  src/routes/AppRoutes.js
  yarn.lock
Labels: enhancement

#13 Ot-139-37-Formulario Edicion Home
  package-lock.json
  package.json
  public/index.html
  src/Components/Backoffice/HomeEdition/HomeFormEdit.jsx
  src/Components/Backoffice/HomeEdition/HomeSlidesFormEdit.jsx
  src/Components/Backoffice/HomeEdition/HomeTitleFormEdit.jsx
  src/Components/Backoffice/HomeEdition/homeFormEdit.css
  src/index.js
  src/routes/AppRoutes.js
  src/shared/style/baseStyle.css
  src/shared/style/colorOng.css
Labels: enhancement

#16 OT139 27 screen contacto creado
  package-lock.json
  package.json
  src/routes/AppRoutes.js
  src/views/Contact/Contact.css
  src/views/Contact/Contact.jsx
  src/views/Contact/Logo.png
  yarn.lock
Labels: enhancement

#10 Ot-139-31-Crear Servicio para Manejar Peticiones Http
  .env
  package-lock.json
  package.json
  src/services/apiService.js
  src/services/authorizationHeaders.js
  src/services/tokenService.js
Labels: enhancement

#47 Fix alert import and token import!
  package-lock.json
  src/services/authorizationHeaders.js
  src/views/NewDetail/NewDetail.jsx
Labels: bug

#19 Ot139 51 listado usuarios admin
  public/index.html
  src/actions/userActions.js
  src/app/store.js
  src/constants/userConstants.js
  src/reducers/userReducer.js
  src/routes/AppRoutes.js
  src/services/usersService.js
  src/views/NewDetail/NewDetail.jsx
  src/views/backOffice/UsersList.jsx
Labels: screen, backoffice

#44 OT139-39 Vincular navbar con screens existentes
  src/App.js
  src/Components/CustomLink/CustomLink.jsx
  src/Components/CustomLink/customLink.css
  src/components/header/Header.jsx
  src/components/header/header.css
Labels: enhancement

#40 OT139-50 Screen Edición Organización (admin) (Frontend)
  src/components/ErrorCard/ErrorCard.jsx
  src/components/LoadingCard/LoadingCard.jsx
  src/routes/AppRoutes.js
  src/services/apiService.js
  src/views/MyProfile/MyProfile.jsx
  src/views/OrganizationEdit/OrganizationEdit.jsx
  src/views/OrganizationEdit/organizationEdit.css
Labels: enhancement

#69 Agregado el export default para Categories
  src/views/backOffice/Categories/Categories.jsx
Labels: bug

#23 OT-139-57-Formulario Edicion Usuario
  src/actions/userActions.js
  src/components/UserEdit/FormEditUser.jsx
  src/components/UserEdit/formedituser.css
  src/routes/AppRoutes.js
  src/services/apiService.js
  src/services/usersService.js
  src/views/MyProfile/MyProfile.jsx
  src/views/backOffice/UsersList.jsx
Labels: enhancement

#26 OT-139-68-Screen-Detalle-de-Actividad
  src/routes/AppRoutes.js
  src/shared/style/colorOng.css
  src/views/About/About.jsx
  src/views/Activities/Activity.jsx
  src/views/Activities/activity.css
  src/views/Home/Home.jsx
  src/views/Home/home.css
  src/views/Home/home.module.css
Labels: enhancement

#76 Se corrigieron multiples typos en imports
  src/actions/contactActions.js
  src/components/UserEdit/FormEditUser.jsx
  src/routes/AppRoutes.js
  src/views/Home/Home.jsx
Labels: bug

#62 OT139-82 Screen Listado de Testimonios (backoffice)
  src/components/TestimonyListEmptyRow/TestimonyListEmptyRow.jsx
  src/components/TestimonyListEmptyRow/testimonyListEmptyRow.css
  src/components/TestimonyListRow/TestimonyListRow.jsx
  src/components/TestimonyListRow/testimonyListRow.css
  src/components/testimonyForm/TestimonyForm.jsx
  src/routes/AppRoutes.js
  src/services/apiService.js
  src/services/testimonyService.js
  src/views/Testimonials/Testimonials.jsx
  src/views/Testimonials/testimonials.css
Labels: enhancement

#37 Ot139 76 listado de contactos
  src/routes/PrivateRoutes/PrivateRoutes.jsx
  src/services/contactsService.js
  src/views/ContactList/ContactList.jsx
Labels: enhancement
